name: Waymo Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:  # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests cloudscraper
      - name: Install dependencies
        run: pip install requests cloudscraper pytz

      - name: Run scraper
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: 445bb640c82a32bc2f4fe38ccb870801
        run: python scraper.py
